### PR TITLE
[Docs - FAQ] Fix for "Cant play some songs after downgrading spotify"

### PR DESCRIPTION
**Pull request by lenicyl**

### CODE REVIEW

**Comment by afonsojramos** [comment]
@lenicyl I have not seen this problem/fix around, can you point me to a place where it has been applied and worked?

**Comment by lenicyl** [comment]
@afonsojramos So this weird bug happened to me today when i was downgrading
I searched it up on the spicetify discord which gave me this solution

[The discord message link from where i found the solution link](https://discord.com/channels/842219447716151306/842818627164962828/919356833548890212)

**Comment by lenicyl** [comment]
Also im unaware if this happens on linux since i dont currently use linux

**Comment by afonsojramos** [comment]
I still think that this needs to be updated with MacOS and Linux paths. Can you check around Discord what would these be?

**Comment by lenicyl** [comment]
> I still think that this needs to be updated with MacOS and Linux paths. Can you check around Discord what would these be?

I am unaware about MacOS and linux fixes, or even if this issue occurs on those OS's
I couldnt really find anything on the discord either.

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
