### PR TITLE
docs: simplify installation process

### LINKED ISSUE #12: Simplify installation process
As a first time user, the installation page can seem a bit daunting.

We should simplify it as best as we can to present the single command for both platforms.

### PR DESCRIPTION
**Pull request by afonsojramos**
Closes #12. One thing that I've always had a trouble with was the installation page.

From now on, most people will only need to see this single page, which I think will be a big improvement.

I have, however, already included the Spicetify Marketplace, so I'd like your approval @CharlieS1103 @khanhas @theRealPadster. You can review the change on the Preview page that Vercel will compile.

### CODE REVIEW

**Comment by afonsojramos** [comment]
New suggestion: 

1. Change the sidebar group `Getting Started` to `Advanced Usage`. 
2. Extract `Simple installation` to outside all the groups and rename to `Installation`.

**Comment by CharlieS1103** [comment]
@afonsojramos Sounds good to me, if you could make the Spicetify marketplace reference a link to the actual GitHub repo it would be appreciated, but all in all, doesn't really matter so up to you.

**Comment by afonsojramos** [comment]
> If you could make the Spicetify marketplace reference a link to the actual GitHub repo

@CharlieS1103 Agreed, but I'd like to keep this simple installation page with as little extra information as possible. So maybe we can add that somewhere else? Do you have any idea where to put it? Maybe we can even create a page just for the Marketplace 🤔

**Comment by theRealPadster** [comment]
> New suggestion:
> 
>     1. Change the sidebar group `Getting Started` to `Advanced Usage`.
> 
>     2. Extract `Simple installation` to outside all the groups and rename to `Installation`.

Wouldn't that leave it with a heading of "advanced usage" with an item called "basic usage" inside? 

Also, did you have a look at the shell script? I did test it myself and it seems to work, but I'm not 100% confident in it (and don't understand/have not vetted the PowerShell one). Just think maybe having a little more testing or eyes on it before going up might be a good idea :)

**Comment by theRealPadster** [comment]
Oh, also, does the spicetify install script add spicetify to the $PATH? Because I know the bash script at least relies on it being there.

**Comment by afonsojramos** [comment]
> Wouldn't that leave it with a heading of "advanced usage" with an item called "basic usage" inside?

Yeah, I guess you're right... Let's leave it as is!

As for the PowerShell script I tested it and it worked, but I can take a closer look at what's inside! :eyes:

**Comment by afonsojramos** [comment]
> Oh, also, does the spicetify install script add spicetify to the $PATH? Because I know the bash script at least relies on it being there.

Yep, it does! I actually just tested it on MacOS ✅

**Comment by theRealPadster** [comment]
> > Oh, also, does the spicetify install script add spicetify to the $PATH? Because I know the bash script at least relies on it being there.
> 
> Yep, it does! I actually just tested it on MacOS ✅

Took a look at the script and it looks like it only adds it to the $PATH on MacOS, since you can guarantee that it's got a `.zshrc`. It doesn't add to $PATH on Linux at all, from what I can tell. I may need to adjust our install script, but I'm not sure if there's a reliable way to know where the spicetify executable is located... And I do want it to work in general, even if you've got it installed in a non-standard location. May have to result to checking if the command exists in the path, and then defaulting to `~/spicetify-cli/spicetify` if not 🤔

**Comment by afonsojramos** [comment]
@theRealPadster if that's the case, don't worry, I'll try to fix it on spicetify-cli's side. Your script should assume that it is added to the path imo!

**Pull request merged**
